apply plugin: 'com.android.application'

android {
    namespace 'app.smashsmashin.authoridassistant'
    compileSdkVersion 34

    defaultConfig {
        applicationId "app.smashsmashin.authoridassistant"
        minSdkVersion 28
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    if(project.hasProperty("signing.properties")
        && new File(project.property("signing.properties")).exists()) {

        Properties props = new Properties()
        props.load(new FileInputStream(new File(project.property("signing.properties"))))

        signingConfigs {
            release {
                storeFile file(props['keystore'])
                keyAlias props['keyAlias']
                storePassword props['keystore.password']
                keyPassword props['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if(project.hasProperty("signing.properties")
                && new File(project.property("signing.properties")).exists()) {
                signingConfig signingConfigs.release
            }
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    
    // Unit Testing Dependencies
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.5.0'
    
    // Instrumentation Testing Dependencies
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test:rules:1.5.0'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'
    androidTestImplementation 'org.mockito:mockito-android:5.5.0'
}
